### PR TITLE
PHP7 compatibility

### PR DESCRIPTION
**Pull request by J-Fricke**
- update ...\String namespace to ...\Text in Handlebars/Helpers.php

Makes ready for php7

### CODE REVIEW

**Comment by JustBlackBird** [comment]
It seems that you should manually set min version of `xamin/handlebars.php` too.

**Comment by faf** [comment]
@J-Fricke, just want to make it clear: once you set the version, we'll merge PR.

**Comment by J-Fricke** [comment]
@JustBlackBird What min value do we need to set for xamin/handlebars.php ?

@fat I did set the version of justblackbird/handlebars.php-helpers in my pull request, are you referring to the comment by @JustBlackBird ?

**Comment by J-Fricke** [comment]
Oh I was just reviewing the xamin/handlebars.php codebase and it looks like we need ~10.3

**Comment by J-Fricke** [comment]
I've pushed the min version for xamin/handlebars.php up as well. Let me know if there is anything else missing.

**Comment by JMCA2** [comment]
@J-Fricke What are the exact steps required to make current mibew version installation work with PHP7? I've tried to apply the changes on "String" and have not being able to make it work.

Thanks!

**Comment by J-Fricke** [comment]
@JMCA2 have you implemented the version bumps and then upgraded your composer dependencies along with update the String namespace to Text as is listed here: https://github.com/Mibew/mibew/pull/176/files

**Comment by faf** [comment]
@J-Fricke Well, everything is fine. Thanks a lot! :)

**Pull request merged**
