### PR TITLE
Improvement/php 7.4

### PR DESCRIPTION
**Pull request by ceckobecko**
Fixes # .

Changes proposed in this pull request:
- These changes are needed in order to fix deprecation notices for PHP 7.4
- Also ignore intellij files for other developers.

@Mibew/core-developers

### CODE REVIEW

**Review by faf — CHANGES_REQUESTED** [review]
I get your point, but it's a bad idea to change the signature of the function. In case of bad incoming value it should return an empty string.

**Review by faf — COMMENTED** [review]
Looks like this breaks the backward compatibility even with PHP 7.3. There should be (at least) changes to ```locales``` and ```translation_edit_save``` routes too. And I'm doubtful about elder versions of PHP (in real world they are still in use, so one have to be very delicate on such issues).

**Comment by ceckobecko** [comment]
> Looks like this breaks the backward compatibility even with PHP 7.3. There should be (at least) changes to `locales` and `translation_edit_save` routes too. And I'm doubtful about elder versions of PHP (in real world they are still in use, so one have to be very delicate on such issues).


I'm not very familiar with the code base, since we are using it as out of the box solution. Could you provide code reference what needs to be changed, so I can do it.

Thank you in advance!

**Review by faf — DISMISSED** [review]

**Comment by faf** [comment]
Looks like it's unable to approve exact commit. :)
The doubtful one is 4c78fd21541556e21297bcec5f5bfb7384783b84 .

I was able to install from scratch with proposed changes only after removing quotes for requirements [here](https://github.com/Mibew/mibew/blob/bfe0065f1cab3a62684f78d6e27d1b1353393236/src/mibew/configs/routing.yml#L719) and [here](https://github.com/Mibew/mibew/blob/bfe0065f1cab3a62684f78d6e27d1b1353393236/src/mibew/configs/routing.yml#L729) .

Maybe there are more hidden issues. And it's only with PHP 7.3, not to mention elder versions that have to be tested too. I'll try to create testing environments for that in the near future.

**Comment by ceckobecko** [comment]
@faf 
Firstly, sorry for the confusion, had to change my email to the one that i'm using in github.

Added simple testing config for docker and tested it with 7.3 could not see any problems in the installation.

The dependencies are depending on PHP 7.2+ as per documentation says:
for symfony/yaml - https://github.com/symfony/yaml/blob/5.x/composer.json

ua-parser/uap-php - https://github.com/ua-parser/uap-php/blob/master/composer.json#L5

And the mibew official page says that PHP 7.3+ is required - https://docs.mibew.org/installation-and-update.html

Also after some more debugging I see that the project raises some deprecation notices  about
https://github.com/Canteen/CanteenHTML5. But this project is archived.

Am I missing something?

**Comment by faf** [comment]
> @faf
> Added simple testing config for docker and tested it with 7.3 could not see any problems in the installation.

There could be nuances with Docker. I'd prefer to test in a native environment, not in Docker container.
 
And e10a4b2c638fdb75bb5e9216ff6d5c667057363d is not related to this PR at all. Please, make separate PRs for separate topics. That would be much more convenient to review and approve.

> The dependencies are depending on PHP 7.2+ as per documentation says:
> for symfony/yaml - https://github.com/symfony/yaml/blob/5.x/composer.json
> 
> ua-parser/uap-php - https://github.com/ua-parser/uap-php/blob/master/composer.json#L5
> 
> And the mibew official page says that PHP 7.3+ is required - https://docs.mibew.org/installation-and-update.html

Oops... That was a typo. It's not 7.3.1, it's 7.1.3. Fixed.

So, in fact proposed changes will cause the cancel of support for 7.1... That's sad. Not catastrophic, but sad.

> Also after some more debugging I see that the project raises some deprecation notices about
> https://github.com/Canteen/CanteenHTML5. But this project is archived.

It's used for button generation. Maybe it will be possible to find some replacement.

Although this very project is not actively developing too. ;)

> Am I missing something?

No idea. :)

**Review by faf — APPROVED** [review]
Checked with PHP 7.{2,3,4}. Works fine.

**Comment by faf** [comment]
@ceckobecko All of your commits were cherry-picked into the master branch. In the near future (after several minor fixes) I'll release a new version of Mibew Messenger with your improvements. Thanks a lot! :)

**Pull request closed without merging**
