### PR TITLE
Clean code with PhpStorm (semicolons)

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by JustBlackBird** [comment]
Well, you've fixed some coding style issues. It's good. But you don't provide a way to control this codding style in future. I believe you should create a gulp task which warn any time a problem with JS codding style is found.

**Comment by stweil** [comment]
That would require a JS analyzer which can be integrated in the gulp workflow. PhpStorm is an IDE, so it won't fit. Do you know any command line tools?

**Comment by JustBlackBird** [comment]
Sure, you can try [JSHint](http://jshint.com), it integrates into gulp workflow with [gulp-jshint](https://github.com/spalger/gulp-jshint). The bad news are it can be hard to make JS code follow new codding standard.

**Comment by JustBlackBird** [comment]
Closed due to inactivity

**Comment by stweil** [comment]
@JustBlackBird, why was this PR not simply applied? It fixed bugs in the code...

**Comment by JustBlackBird** [comment]
Code style is not actually a bug. Also the PR needs more work to introduce a mean to control code style automatically.

**Comment by stweil** [comment]
I am not talking about coding style here.
A missing semicolon is a bug in any programming language. Most JavaScript machines tolerate some kinds of errors, but you cannot rely on this tolerance. Adding automated tests is fine, but a different job which can be handled in another PR.

**Comment by JustBlackBird** [comment]
Missing semicolon in JavaScript is not a bug. There is only few cases there the semicolon is mandatory. And it's not something that depends on a JavaScript engine's implementation. It's something written in ECMAScript standard that has to be followed by all JS engines manufacturers. 

If you don't believe me just read this [post](http://blog.izs.me/post/2353458699/an-open-letter-to-javascript-leaders-regarding) from Isaac Z. Schlueter. It highlights cases when the semicolon is really needed.

I'm sorry, but I still believe that the PR is about codding style, which is _extremely important_ in a big project like Mibew, but without an automated code style checker we cannot guarantee all the semicolons you've introduced will stay after codebase changes.

**Comment by stweil** [comment]
Thanks for this information. I did not know that the ECMAScript standard defines this behavior, but it does: [Chapter 11.9.1](http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-262.pdf) describes the _Rules of Automatic Semicolon Insertion_ . So if we don't put the semicolons which were requested by PhpStorm into the code, there are still "virtual" semicolons inserted at run time by the JavaScript machine – that's really strange, but obviously a well defined feature of the language.

The missing real semicolons still make static code analysis harder, because it's necessary to ignore lots of error messages caused by that.

**Comment by JustBlackBird** [comment]
I think it's configurable in PHPStorm somehow (personally I didn't use it much so can only guess).

If you're interested in code style errors fixing I could add a lint task for building process with rules I believe should be used in Mibew. But I don't have much time to fix all coding styles issues right now.

**Comment by stweil** [comment]
Nor do I, so I'm afraid that coding style issues will have to wait. :-)

**Pull request closed without merging**
